apiVersion: v1
kind: Service
metadata:
  name: osp-service
spec:
  selector:
    app: order-service-provider
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082   # gRPC port
      targetPort: 8082