apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: provider-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service-provider
  template:
    metadata:
      labels:
        app: order-service-provider
    spec:
      containers:
        - name: service
          image: gowgi/osp:1.0.0
          ports:
            - containerPort: 8082